title: "Test Blog"
remote_theme: "mmistakes/minimal-mistakes"

# 필수 플러그인
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

# 빌드 에러 방지
include: ["_pages", "_posts"]
exclude: ["Gemfile", "Gemfile.lock", "node_modules", "vendor"]
