# 테마 설정
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# 사이트 정보
title: "DevSight"
locale: "ko-KR"
url: "https://debugjo.github.io"
baseurl: "" # 절대 빈칸!

# 빌드 설정
include: ["assets", "_pages", "_posts"]
exclude: ["vendor", ".bundle", "Gemfile", "Gemfile.lock", "node_modules"]

# Sass 설정 (중요: sass_dir 항목을 절대 넣지 마세요)
sass:
  style: compressed

# 플러그인
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap

# 기본 레이아웃 적용
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      toc: true
      toc_sticky: true

# 페이지네이션
paginate: 5
paginate_path: /page:num/

exclude:
  - vendor/
  - .github/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - docs/          # 테마 샘플 문서 폴더 제외
  - test/          # 테마 테스트 폴더 제외
  - README.md
  - LICENSE

author:
  name   : "DevSight"
  avatar : "/assets/images/logo.png"
  bio    : "Software Engineer / Developer"

sidebar:
  nav: "main" # navigation.yml의 main 메뉴를 사이드바에 연결

toc: true
toc_label: "Contents"
toc_sticky: true  
